export const FETCH_GOALS_REQUESTED = 'FETCH_GOALS_REQUESTED'
export const FETCH_GOALS_SUCCEED = 'FETCH_GOALS_SUCCEED'
export const FETCH_GOALS_FAILED = 'FETCH_GOALS_FAILED'
export const CREATE_GOAL = 'CREATE_GOAL'
