export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const FACEBOOK_LOGIN_SUCCEED = 'FACEBOOK_LOGIN_SUCCEED'
export const FACEBOOK_LOGIN_FAILED = 'FACEBOOK_LOGIN_FAILED'
